### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by banana16314** [IcarusWizard/MAE#1]
你好，我在运行python mae_pretrain.py的时候遇到了这个问题：
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "mae_pretrain.py", line 44, in <module>
    lr_scheduler = torch.optim.lr_scheduler.LambdaLR(optim, lr_lambda=lr_func, verbose=True)
TypeError: __init__() got an unexpected keyword argument 'verbose'
请问这个应该怎么处理呢？

**Comment by IcarusWizard** [comment]
可能你的torch版本太老了？我用的是1.9.1版本。

**Comment by banana16314** [comment]
谢谢了！我去试试。
