### ISSUE TITLE
What are the versions you worked with, keep getting errors

### ISSUE THREAD

**Issue by BattashB** [IcarusWizard/MAE#12]
Hi, I'm getting a lot of errrors like:
`AttributeError: 'Mlp' object has no attribute 'drop1'`
or 
`AttributeError: 'Block' object has no attribute 'drop_path1'`
Its probably something non compatible between timm and pytorch, any idea whta are the versions you worked with?
It happend only in train_classifier.py.
Thanks!

**Comment by IcarusWizard** [comment]
Hey @BattashB,

Sorry for your encounter a version problem. I should have documented them more detailed.

I always use the lastest version for developing. So by the time I develop this project, the torch version should be 1.10.1 and the timm should be 0.4.12. I have tested them in a new envrionment from scratch and worked smoothly.

**Comment by Wonder1905** [comment]
Thanks a lot!
