### ISSUE TITLE
how to make the masked patches not random

### ISSUE THREAD

**Issue by wenhaowang1995** [IcarusWizard/MAE#14]
Hi, is there any possible way to fix the position of masked patches? (for example. make all masked patches together into the middle of the image instead of spreading round the image randomly)

Thank you for your help!

**Comment by IcarusWizard** [comment]
Hi @wenhaowang1995. You can re-write the [PatchShuffle](https://github.com/IcarusWizard/MAE/blob/main/model.py#L20) class to implement a different masking scheme.

**Comment by wenhaowang1995** [comment]
> Hi @wenhaowang1995. You can re-write the [PatchShuffle](https://github.com/IcarusWizard/MAE/blob/main/model.py#L20) class to implement a different masking scheme.

oh, I see, thanks a lot!
