### ISSUE TITLE
最后你得重建图像是怎么来的？

### ISSUE THREAD

**Issue by impeccable992** [IcarusWizard/MAE#16]

**Comment by impeccable992** [comment]
最后你得重建图像是怎么来的？

**Comment by IcarusWizard** [comment]
输入图像先经过mask操作随机去除75%的patch，没被mask的patch经过encoder得到latent token，之后填充mask token进入decoder预测被mask掉的patch，再和没有mask的patch组合形成重建图像。

更详细的细节请参考代码或原始论文。
