### ISSUE TITLE
Suspected minor bug

### ISSUE THREAD

**Issue by Hong753** [IcarusWizard/MAE#17]
Hi, there is a minor bug in the MAE_Decoder implementation.
The input to the forward function (line 103 in model.py) has features.shape[0] == 1 + t (where 1 refers to the cls_token, and t the number of unmasked tokens).
Then, in line 117: mask[T:] = 1, should actually be mask[T-1:] = 1, since the mask was created without accounting for the cls_token.

**Comment by IcarusWizard** [comment]
Thanks a lot for catching this! The bug has been fixed now.
