### ISSUE TITLE
resource requirement

### ISSUE THREAD

**Issue by pangzhiyu** [IcarusWizard/MAE#18]
我想请问一下学长你目前复现这个工作用的什么GPU？大概要跑完要多久？

**Comment by IcarusWizard** [comment]
你好，我当时是用2080ti进行的训练，预训练需要20h左右，分类器训练需要2h左右。

**Comment by pangzhiyu** [comment]
好的，谢谢学长




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IcarusWizard/MAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IcarusWizard/MAE] 学长你好 (Issue #18)





 
你好，我当时是用2080ti进行的训练，预训练需要20h左右，分类器训练需要2h左右。
