### ISSUE TITLE
Could  you provide a one-dimensional MAE  implementation in pytorch?

### ISSUE THREAD

**Issue by bigdaronlee163** [IcarusWizard/MAE#4]

**Comment by IcarusWizard** [comment]
Hi @bigdaronlee163. It should be easy to convert the current implementation to other data forms. The only thing you need to worry about is to define the so-called "tokenizer" for your data. For example, MAE use [patch convolusion](https://github.com/IcarusWizard/MAE/blob/main/model.py#L53) as the tokenizer to convert an image to a sequence of tokens. 

I don't know what exactly the `one-dimensional` data you refer to? Is it just a D-dimensional vector or some sequence like a music MIDI file? Give me more details about what you want to achieve, and we can discuss the best way to implement it.
